application:
  audience: {from auth0}
  client-origin-url: http://localhost:4040

server:
  error:
    whitelabel:
      enabled: false
  port: 6060

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: {from auth0}
  web:
    resources:
      add-mappings: false
  datasource:
    url: 'jdbc:postgresql://localhost:5432/vas_db'
    username: postgres
    password: '1234'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: true

#  sql:
#    init:
#      mode: always

logging:
  level:
    org:
      springframework:
        security: TRACE

